import React, { useState, useEffect, useRef } from 'react';
import io from 'socket.io-client';
import { motion, AnimatePresence } from 'framer-motion';
import { downloadImage } from '../utils';
import { Loader } from '../Components';
import toast, { Toaster } from 'react-hot-toast';
import config from '../config';

const CollabRoom = () => {
  const userName = localStorage.getItem('userName') || 'Guest';
  
  const socketRef = useRef(null);
  const typingTimeoutRef = useRef(null);
  const chatScrollRef = useRef(null);

  // New State for Tabs (Join vs Create)
  const [activeTab, setActiveTab] = useState('join'); // 'join' or 'create'

  const [room, setRoom] = useState("");
  const [inRoom, setInRoom] = useState(false);
  const [message, setMessage] = useState("");
  const [messageList, setMessageList] = useState([]);
  const [typingStatus, setTypingStatus] = useState("");
  const [activeUsers, setActiveUsers] = useState([]);

  const [prompt, setPrompt] = useState("");
  const [sharedImage, setSharedImage] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [statusMsg, setStatusMsg] = useState("");

  useEffect(() => {
    socketRef.current = io(config.backendUrl);

    // -- Standard Listeners --
    socketRef.current.on("receive_message", (data) => setMessageList((list) => [...list, data]));
    socketRef.current.on("receive_shared_image", (data) => {
      setSharedImage(data.photo);
      setPrompt(data.prompt); 
    });
    socketRef.current.on("receive_prompt_sync", (text) => setPrompt(text));
    socketRef.current.on("update_user_list", (users) => setActiveUsers(users));

    socketRef.current.on("generation_status", (data) => {
      if(data.status === 'loading') {
        setIsGenerating(true);
        setStatusMsg(`${data.user} is generating...`);
      } else if (data.status === 'success') {
        setIsGenerating(false);
        setStatusMsg(`Generated by ${data.user}`);
        toast.success(`New masterpiece by ${data.user}!`);
      } else if (data.status === 'error') {
        setIsGenerating(false);
        toast.error(data.message || "Generation failed");
      }
    });

    socketRef.current.on("display_typing", (data) => {
      setTypingStatus(`${data.author} is typing...`);
      if (typingTimeoutRef.current) clearTimeout(typingTimeoutRef.current);
      typingTimeoutRef.current = setTimeout(() => setTypingStatus(""), 3000);
    });

    // -- NEW: Security & Room Logic --
    socketRef.current.on("error_join", (msg) => {
        toast.error(msg);
        setInRoom(false);
        setRoom(""); // Reset invalid room
    });

    socketRef.current.on("room_created", (roomId) => {
        setRoom(roomId);
        socketRef.current.emit("join_room", { room: roomId, user: userName });
        setInRoom(true);
        toast.success(`Room Created: ${roomId}`);
    });

    return () => socketRef.current.disconnect();
  }, [userName]);

  useEffect(() => {
    chatScrollRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messageList, typingStatus]);

  // Handler: Join Existing
  const joinRoom = () => {
    if (room !== "" && socketRef.current) {
      socketRef.current.emit("join_room", { room, user: userName });
      setInRoom(true); 
    } else {
        toast.error("Please enter a Room ID");
    }
  };

  // Handler: Create New
  const createRoom = () => {
      if (socketRef.current) {
          socketRef.current.emit("create_room", { user: userName });
      }
  };

  // Helper: Copy ID
  const copyRoomId = () => {
      navigator.clipboard.writeText(room);
      toast.success("Room ID copied!");
  };

  const sendMessage = async () => {
    if (message !== "" && socketRef.current) {
      const messageData = {
        room: room,
        author: userName,
        message: message,
        time: new Date(Date.now()).getHours() + ":" + new Date(Date.now()).getMinutes(),
      };
      await socketRef.current.emit("send_message", messageData);
      setMessageList((list) => [...list, messageData]);
      setMessage("");
    }
  };

  const handleTyping = (e) => {
    setMessage(e.target.value);
    if (socketRef.current) socketRef.current.emit("typing", { room, author: userName });
  };

  const handlePromptChange = (e) => {
    const newText = e.target.value;
    setPrompt(newText);
    if (socketRef.current) socketRef.current.emit("sync_prompt", { room, text: newText });
  };

  const handleCollaborativeGenerate = () => {
    if(!prompt) return toast.error("Please enter a prompt first");
    if(socketRef.current) socketRef.current.emit("collaborative_generate", { prompt, room, user: userName });
  };

  return (
    // UPDATED: h-[100dvh] ensures it fits mobile screens perfectly without address bar issues
    // UPDATED: padding adjusted for mobile (pt-20 px-2) vs desktop (pt-28 px-8)
    <div className="h-[100dvh] w-full bg-[#f9fafe] pt-20 pb-2 px-2 sm:px-4 lg:pt-28 lg:pb-4 lg:px-8 flex flex-col overflow-hidden">
      
      <Toaster position="top-center" reverseOrder={false} />

      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        {/* UPDATED: Fixed blob sizes for mobile */}
        <div className="absolute top-[-10%] left-[-10%] w-[300px] h-[300px] sm:w-[500px] sm:h-[500px] bg-purple-400/20 blur-[80px] sm:blur-[120px] rounded-full mix-blend-multiply" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[300px] h-[300px] sm:w-[500px] sm:h-[500px] bg-indigo-400/20 blur-[80px] sm:blur-[120px] rounded-full mix-blend-multiply" />
      </div>

      <AnimatePresence mode="wait">
        {!inRoom ? (
          /* --- ENTRY SCREEN (TABBED) --- */
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            // UPDATED: m-auto ensures centering, p-6 for mobile
            className="relative z-10 w-full max-w-md bg-white/70 backdrop-blur-xl border border-white/50 shadow-2xl rounded-3xl p-6 sm:p-8 text-center m-auto"
          >
            <div className="mb-6">
               <h2 className="text-2xl sm:text-3xl font-bold text-gray-800 tracking-tight">Studio Access</h2>
               <p className="text-sm sm:text-base text-gray-500 mt-2">Collaborate with friends in real-time</p>
            </div>

            {/* TABS */}
            <div className="flex p-1 bg-gray-100 rounded-xl mb-6">
                <button 
                    onClick={() => setActiveTab('join')}
                    className={`flex-1 py-2 text-sm font-semibold rounded-lg transition-all ${activeTab === 'join' ? 'bg-white shadow-sm text-indigo-600' : 'text-gray-500 hover:text-gray-700'}`}
                >
                    Join Room
                </button>
                <button 
                    onClick={() => setActiveTab('create')}
                    className={`flex-1 py-2 text-sm font-semibold rounded-lg transition-all ${activeTab === 'create' ? 'bg-white shadow-sm text-indigo-600' : 'text-gray-500 hover:text-gray-700'}`}
                >
                    Create New
                </button>
            </div>

            {activeTab === 'join' ? (
                <div className="space-y-4">
                  <input
                    className="w-full bg-white/50 border border-gray-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 rounded-xl px-5 py-4 text-lg outline-none transition-all placeholder:text-gray-400 text-center uppercase tracking-widest"
                    type="text"
                    placeholder="ENTER CODE"
                    maxLength={6}
                    onChange={(e) => setRoom(e.target.value.toUpperCase())}
                    onKeyDown={(e) => e.key === 'Enter' && joinRoom()}
                  />
                  <button 
                    onClick={joinRoom}
                    className="w-full py-4 bg-gradient-to-r from-indigo-600 to-fuchsia-600 text-white rounded-xl font-semibold text-lg shadow-xl shadow-indigo-500/30 hover:scale-[1.02] active:scale-[0.98] transition-all"
                  >
                    Join Session
                  </button>
                </div>
            ) : (
                <div className="space-y-4">
                    <div className="p-6 bg-indigo-50/50 rounded-2xl border border-indigo-100">
                        <div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center mx-auto mb-3 text-indigo-600">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-6 h-6">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                            </svg>
                        </div>
                        <p className="text-sm text-gray-600">Start a new private session. You'll get a unique code to share.</p>
                    </div>
                    <button 
                        onClick={createRoom}
                        className="w-full py-4 bg-gray-900 text-white rounded-xl font-semibold text-lg shadow-lg hover:scale-[1.02] active:scale-[0.98] transition-all"
                    >
                        Create & Enter
                    </button>
                </div>
            )}
          </motion.div>
        ) : (
          /* --- MAIN COLLAB INTERFACE --- */
          /* UPDATED: Flex-col for mobile (stacking), Grid for desktop (side-by-side) */
          <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="relative z-10 w-full max-w-7xl h-full mx-auto flex flex-col lg:grid lg:grid-cols-[1fr_350px] gap-3 lg:gap-6"
          >
            {/* LEFT AREA: CANVAS & PROMPT */}
            {/* UPDATED: On mobile, takes 45% height. On desktop, full height */}
            <div className="flex flex-col gap-3 lg:gap-6 h-[45%] lg:h-full min-h-0">
              
              {/* Header Bar */}
              <div className="flex items-center justify-between bg-white/70 backdrop-blur-md p-2 lg:p-4 rounded-xl lg:rounded-2xl border border-white/50 shadow-sm flex-shrink-0">
                <div className="flex items-center gap-4">
                  <div className="flex items-center gap-2 px-2 lg:px-3 py-1.5 bg-white rounded-lg border border-gray-100 shadow-sm">
                      <span className="hidden sm:inline text-xs font-bold text-gray-500 uppercase">Room ID</span>
                      <span className="font-mono font-bold text-indigo-600 text-sm lg:text-lg tracking-widest">{room}</span>
                      <button onClick={copyRoomId} className="ml-2 text-gray-400 hover:text-gray-600 p-1" title="Copy Code">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 17.25v3.375c0 .621-.504 1.125-1.125 1.125h-9.75a1.125 1.125 0 01-1.125-1.125V7.875c0-.621.504-1.125 1.125-1.125H6.75a9.06 9.06 0 011.5.124m7.5 10.376h3.375c.621 0 1.125-.504 1.125-1.125V11.25c0-4.46-3.243-8.161-7.5-8.876a9.06 9.06 0 00-1.5-.124H9.375c-.621 0-1.125.504-1.125 1.125v3.5m7.5 10.375H9.375a1.125 1.125 0 01-1.125-1.125v-9.25m12 6.625v-1.875a3.375 3.375 0 00-3.375-3.375h-1.5" />
                        </svg>
                      </button>
                  </div>
                </div>
                {statusMsg && (
                  <span className="px-2 lg:px-3 py-1 bg-indigo-50 text-indigo-600 text-xs lg:text-sm font-medium rounded-full border border-indigo-100 animate-fade-in truncate max-w-[120px] lg:max-w-none">
                    {statusMsg}
                  </span>
                )}
              </div>

              {/* Main Image Display */}
              <div className="flex-grow min-h-0 bg-white/40 backdrop-blur-sm border-2 border-dashed border-indigo-200/50 rounded-2xl lg:rounded-3xl overflow-hidden relative group transition-all hover:border-indigo-300">
                {sharedImage ? (
                  <>
                    <img src={sharedImage} alt="Shared Art" className="w-full h-full object-contain" />
                    <div className="absolute top-2 right-2 lg:top-4 lg:right-4 flex gap-2 opacity-100 lg:opacity-0 lg:group-hover:opacity-100 transition-opacity duration-300">
                      <button 
                        onClick={() => downloadImage(`collab-${Date.now()}`, sharedImage)}
                        className="bg-white/90 backdrop-blur text-gray-700 p-2 lg:p-3 rounded-xl shadow-lg hover:bg-white hover:text-indigo-600 transition-colors"
                        title="Download"
                      >
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-5 h-5">
                          <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M12 3v13.5M8.25 12.75L12 16.5l3.75-3.75" />
                        </svg>
                      </button>
                    </div>
                  </>
                ) : (
                  <div className="absolute inset-0 flex flex-col items-center justify-center text-gray-400 p-4 text-center">
                    <div className="w-16 h-16 lg:w-20 lg:h-20 bg-gray-100 rounded-full flex items-center justify-center mb-4">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8 lg:w-10 lg:h-10">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z" />
                      </svg>
                    </div>
                    <p className="text-base lg:text-lg font-medium">Your canvas is empty</p>
                    <p className="text-xs lg:text-sm opacity-70">Start typing a prompt below!</p>
                  </div>
                )}
                
                {isGenerating && (
                  <div className="absolute inset-0 bg-white/60 backdrop-blur-md flex flex-col items-center justify-center z-20">
                    <Loader />
                    <p className="mt-4 text-indigo-600 font-medium animate-pulse text-sm">Creating...</p>
                  </div>
                )}
              </div>

              {/* Prompt Bar */}
              <div className="bg-white/80 backdrop-blur-xl p-2 rounded-xl lg:rounded-2xl shadow-lg border border-white/50 flex gap-2 flex-shrink-0">
                <input
                  value={prompt}
                  onChange={handlePromptChange}
                  placeholder="Describe image..."
                  className="flex-grow bg-transparent px-3 py-2 lg:px-4 lg:py-3 text-sm lg:text-base text-gray-800 placeholder:text-gray-400 outline-none font-medium min-w-0"
                />
                <button
                  onClick={handleCollaborativeGenerate}
                  disabled={isGenerating}
                  className="bg-gray-900 text-white px-3 py-2 lg:px-6 lg:py-3 rounded-lg lg:rounded-xl font-semibold hover:bg-indigo-600 disabled:opacity-50 disabled:hover:bg-gray-900 transition-colors flex items-center gap-2 flex-shrink-0"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4 lg:w-5 lg:h-5">
                    <path d="M15.98 1.804a1 1 0 00-1.96 0l-.24 1.192a1 1 0 01-.784.785l-1.192.238a1 1 0 000 1.96l1.192.238a1 1 0 01.785.785l.238 1.192a1 1 0 001.96 0l.238-1.192a1 1 0 01.785-.785l1.192-.238a1 1 0 000-1.96l-1.192-.238a1 1 0 01-.785-.785l-.238-1.192zM6.949 5.684a1 1 0 00-1.898 0l-.683 5.618-5.618.682a1 1 0 000 1.898l5.618.683.683 5.618a1 1 0 001.898 0l.683-5.618 5.618-.683a1 1 0 000-1.898l-5.618-.683-.683-5.618z" />
                  </svg>
                  <span className="hidden sm:inline">Generate</span>
                </button>
              </div>
            </div>

            {/* RIGHT AREA: CHAT PANEL */}
            {/* UPDATED: On mobile, takes remaining height (55%). Desktop takes full height */}
            <div className="bg-white/80 backdrop-blur-xl border border-white/50 rounded-2xl lg:rounded-3xl shadow-xl flex flex-col overflow-hidden h-full min-h-0 flex-grow">
              
              {/* USER LIST HEADER */}
              <div className="p-3 lg:p-4 border-b border-gray-100 bg-white/50 flex-shrink-0 flex flex-col gap-2 lg:gap-3">
                <div className="flex justify-between items-center">
                  <h3 className="font-bold text-gray-800 text-sm lg:text-base">Team Chat</h3>
                  <div className="flex -space-x-2 overflow-hidden">
                    {/* Display Avatars */}
                    {activeUsers.slice(0, 5).map((user) => (
                      <div 
                        key={user.id} 
                        title={user.name}
                        className="inline-block h-6 w-6 lg:h-8 lg:w-8 rounded-full ring-2 ring-white bg-gradient-to-tr from-indigo-500 to-fuchsia-500 flex items-center justify-center text-[10px] lg:text-xs text-white font-bold"
                      >
                        {user.name.charAt(0).toUpperCase()}
                      </div>
                    ))}
                    {activeUsers.length > 5 && (
                        <div className="inline-block h-6 w-6 lg:h-8 lg:w-8 rounded-full ring-2 ring-white bg-gray-200 flex items-center justify-center text-[8px] lg:text-xs text-gray-600 font-bold">
                           +{activeUsers.length - 5}
                        </div>
                    )}
                  </div>
                </div>
                <p className="text-[10px] lg:text-xs text-gray-500 truncate">
                  {activeUsers.length} Online: {activeUsers.map(u => u.name).join(", ")}
                </p>
              </div>

              {/* Messages Area */}
              <div className="flex-grow overflow-y-auto p-3 lg:p-4 space-y-3 lg:space-y-4 scrollbar-hide">
                {messageList.map((msg, index) => {
                  const isMe = msg.author === userName;
                  return (
                    <div key={index} className={`flex flex-col ${isMe ? "items-end" : "items-start"}`}>
                      <div className={`
                        max-w-[85%] px-3 py-2 lg:px-4 lg:py-2.5 rounded-2xl text-xs lg:text-sm font-medium shadow-sm
                        ${isMe 
                          ? "bg-gradient-to-br from-indigo-600 to-violet-600 text-white rounded-br-none" 
                          : "bg-white border border-gray-100 text-gray-700 rounded-bl-none"}
                      `}>
                        <p>{msg.message}</p>
                      </div>
                      <span className="text-[9px] lg:text-[10px] text-gray-400 mt-1 px-1">
                        {isMe ? 'You' : msg.author} • {msg.time}
                      </span>
                    </div>
                  );
                })}
                <div ref={chatScrollRef} />
              </div>

              {/* Typing Indicator */}
              <AnimatePresence>
                {typingStatus && (
                  <motion.div 
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: 10 }}
                    className="px-4 py-1 text-[10px] lg:text-xs text-indigo-500 font-medium bg-indigo-50/50 flex-shrink-0"
                  >
                    {typingStatus}
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Input Area */}
              <div className="p-2 lg:p-3 bg-white border-t border-gray-100 flex-shrink-0">
                <div className="flex items-center gap-2 bg-gray-50 border border-gray-200 rounded-full px-3 py-2 lg:px-4 lg:py-2 focus-within:border-indigo-300 focus-within:ring-2 focus-within:ring-indigo-100 transition-all">
                  <input
                    value={message}
                    onChange={handleTyping}
                    onKeyDown={(e) => e.key === 'Enter' && sendMessage()}
                    placeholder="Type..."
                    className="flex-grow bg-transparent outline-none text-xs lg:text-sm text-gray-700"
                  />
                  <button 
                    onClick={sendMessage}
                    className={`p-1.5 lg:p-2 rounded-full transition-colors ${message ? 'text-indigo-600 hover:bg-indigo-100' : 'text-gray-400'}`}
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4 lg:w-5 lg:h-5 transform rotate-90">
                      <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z" />
                    </svg>
                  </button>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};


export default CollabRoom;
